# This file was generated by GoReleaser. DO NOT EDIT.
class Grouse < Formula
  desc "A diff tool for Hugo websites."
  homepage "https://github.com/capnfabs/grouse"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/capnfabs/grouse/releases/download/v0.1.1/grouse_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "30d03b7fb152e01e9d739a0a44ac449ba3ce19a62bb21c7905f2f2d40b8d1c95"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/capnfabs/grouse/releases/download/v0.1.1/grouse_0.1.1_Linux_x86_64.tar.gz"
      sha256 "2dd473c85c33da88288ead978489de3d55e07c40a04baa43e67cc0a1567d51cd"
    end
  end

  def install
    bin.install "grouse"
  end
end
