# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grouse < Formula
  desc "A diff tool for Hugo websites."
  homepage "https://github.com/capnfabs/grouse"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/capnfabs/grouse/releases/download/v0.2.1/grouse_0.2.1_Darwin_arm64.tar.gz"
      sha256 "8a5e852050d8370ac1cef4744fab74b1d4b52b982725292880f242b27f4f84cd"

      def install
        bin.install "grouse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/capnfabs/grouse/releases/download/v0.2.1/grouse_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "03a64252f3ca58432d0227599390d00075a4638e2044cd142210ea252b8e6fbd"

      def install
        bin.install "grouse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/capnfabs/grouse/releases/download/v0.2.1/grouse_0.2.1_Linux_arm64.tar.gz"
      sha256 "f2096a5b22273255fb2477d387e51d530826323f82b19b6ea7ab1a93bfa5a486"

      def install
        bin.install "grouse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/capnfabs/grouse/releases/download/v0.2.1/grouse_0.2.1_Linux_x86_64.tar.gz"
      sha256 "1a270b19bf1f7d085056be97a27ee7b1674a2a0b47cac5f3986a5fa1061da0c0"

      def install
        bin.install "grouse"
      end
    end
  end
end
